### ISSUE TITLE
It's not clear that the zoom icon on a library is actually 'show in finder'

### ISSUE THREAD

**Issue by equivalentideas** [e-e-e/dat-library#14]
I had no idea what that button would do.

![screen shot 2017-08-01 at 4 04 47 pm](https://user-images.githubusercontent.com/1239550/28811528-38ad55dc-76d3-11e7-813d-a29c32e244c5.png)

May I suggest that the text "show in finder" would be more useful that the icon here  (for MacOS at least, I'm sure other OS's have an equivalent concept). It would help people discover that feature without having to click the button.

Also the common meaning of that icon might not easily sit conceptually with what the button does—but this is my first time using the app (great work by the way ❤️ ).

**Comment by e-e-e** [comment]
@equivalentideas really agree with you! Its a by product of using http://element.eleme.io/#/. We decided to use it to get the basic functionality up quickly - but are now hitting a number of walls with it. Positive is that the fix to this is in progress ATM - https://github.com/e-e-e/dat-library-ui. We are building our own simple ui library so we have more control over these aspects.

**Comment by e-e-e** [comment]
For now - tried to make it more obvious - like so:

![screen shot 2017-08-01 at 9 42 01 pm](https://user-images.githubusercontent.com/12589522/28823762-882a19f4-7702-11e7-86dd-3ed50b32d3d5.png)

The commit that addresses this is https://github.com/e-e-e/dat-library/commit/5aae562b983d650805d819e75ac381ffb6c8050f, and will be included in the next release.

:)
