### ISSUE TITLE
I just added a new library by key, but under browse there are no texts for it, it's not clear why

### ISSUE THREAD

**Issue by equivalentideas** [e-e-e/dat-library#15]
I don't think it's because the library actually has no texts, because a reliable source gave me the key.

Not sure what's going on, but wanted to raise this issue to mark the confusing situation as a bug in the interface here.

Maybe one way to work out how to improve this would be to list the reasons why a library would have no texts after importing from a key.

**Comment by equivalentideas** [comment]
Aha, I get the feeling that I have 0 texts in that library because I haven't downloaded the metadata from that library:

![screen shot 2017-08-01 at 4 21 23 pm](https://user-images.githubusercontent.com/1239550/28811935-966762e2-76d5-11e7-9b06-06d3beaa3871.png)

If this is correct, maybe that would have been clearer if on the browse page it explained something like "0 texts for monoskop library. Texts will be listed here once you've downloaded the metadata for this library".

Or maybe something on the library page for that library saying "You'll be able to browse the texts in this library once the metadata has downloaded". Then just don't list libraries on the browse page filters that have no metadata.

It might also be useful to explain why I haven't downloaded the metadata and what I can do about that :)

**Comment by equivalentideas** [comment]
> Or maybe something on the library page for that library saying "You'll be able to browse the texts in this library once the metadata has downloaded". Then just don't list libraries on the browse page filters that have no metadata.
> 
> It might also be useful to explain why I haven't downloaded the metadata and what I can do about that :)

I feel like that solution might be clearer than the other idea :)

**Comment by e-e-e** [comment]
Totally agree and easy to implement. Will try and get a fix in the next release.

**Comment by e-e-e** [comment]
This will also now be fixed in the next release.

These two commits should fix the issue.

- https://github.com/e-e-e/dat-library/commit/026835a531a0dda7344ad84cfee7e2b33dcab333
- https://github.com/e-e-e/dat-library/commit/a85e80a93ec0d3d92a913b17543787ea6de31047

I went with your last suggestion, as I think its clearest too.
