### ISSUE TITLE
How do I update to the latest version of the software?

### ISSUE THREAD

**Issue by equivalentideas** [e-e-e/dat-library#18]
It's not clear to me how I can get the latest release. It would be good to mention this in the app somewhere, especially at this early stage when there's lots of updates for people using it 🌲

**Comment by e-e-e** [comment]
Ah if you have downloaded the app after v0.1.0 you should automatically be notified when a new version is available. The alert contains a link to the latest version for downlaod. Do you think we also need to link to the github from the app somehow?

**Comment by e-e-e** [comment]
also its hard to see - but we are working on a restructure of dat-cardcat at the moment - so the next release is taking a bit longer. We are working on getting advanced metadata from the opf files, and generally dealing with files/text better.
