### ISSUE TITLE
Could not get running locally

### ISSUE THREAD

**Issue by karissa** [e-e-e/dat-library#3]
On Node 8.1.2, running:
```
$ npm run dev
```

Gives:
```
┏ Electron -------------------

  2017-07-20 17:32:03.896 Electron Helper[40107:5347919] Couldn't set selectedTextBackgroundColor from default ()

┗ ----------------------------

```

I followed the instructions on the README.

Also, seems like `npm run cli` has been removed from package.json. Is this still applicable?

**Comment by e-e-e** [comment]
Thanks so much for helping us test @karissa.
The read me is a bit out of date - we need to update that ASAP.

Basically the cli was moved into its own separate module - [dat-cardcat](https://www.npmjs.com/package/dat-cardcat).
As for that console error - I also get that locally but it does not stop the app from starting. I use node 6, so will try to replicate on 8. But also could I ask - what OS are you running?

**Comment by e-e-e** [comment]
I am going to close this issue as other people have not experienced an issue, and it appears to be working for others.
If you are still having problems @karissa please let us know and I will reopen.
