### ISSUE TITLE
Doesn't work on windows.

### ISSUE THREAD

**Issue by e-e-e** [e-e-e/dat-library#5]
Lots of issues - all potentially caused by path.

@sdockray noted:
> it installs and opens, and people can even import a key, but no metadata is imported. but they can download the whole library. but there are no download events. (i wonder if this is as simple as paths not parsing correctly or something). also created dat makes a key, but i haven't been able to see it appear on network

**Comment by sdockray** [comment]
It does work now - issues remain, but they are smaller and should get their own issues filed
