### ISSUE TITLE
More feedback on importing

### ISSUE THREAD

**Issue by sdockray** [e-e-e/dat-library#9]
When importing from Info page, there is very little feedback to let you know what's happening.

**Comment by e-e-e** [comment]
My thought was to automatically take the user to the libraries page with that library open. so they can see the importing progress bar.

**Comment by sdockray** [comment]
We should also display ul/dl speeds I think

**Comment by e-e-e** [comment]
dl and ul speeds are done - just need to make it clearer when you first import a library from the info section that content is now available.

**Comment by e-e-e** [comment]
We actually inadvertently did this without addressing this issue directly. I am going to close it.
